console.log("Rodando o sistema de gerenciamento de jogos")
console.log("Aplicação está se conectando ao banco de dados")
console.log("Adição de console para dar commit")
console.log("Armando deu o commit!")
console.log("Alteração armando dia 19/09/2023")
console.log("Treinando mais um commit")